name: gtel_erp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  flutter_screenutil: ^5.9.3
  get: ^4.7.3
  font_awesome_flutter: ^10.9.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  pdf: ^3.11.3
  printing: ^5.14.2
  http: ^1.6.0
  fl_chart: ^1.1.0
  firebase_auth: ^6.1.3

# THIS IS THE CRITICAL FIX SECTION
dependency_overrides:
  vector_math: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true